repo_id: "Kytolly/FollowBench"
device: "cuda"
assets:
  path: "E:/xqy/FollowBench"
output:
  path: "output/"
rules:
  clip_len: 49
  fps: 60
  height: 704
  width: 1280
submission:
  source_path: "E:/xqy/output/output_kling/test_unseen"
  json_path: "templates/submission_kling.json"
meta:
  team_name: "Kytolly"
  model_name: "Kling AI"
  split: "test_unseen"
  contact: "kytolly.xqy@gmail.com"
metrics:
  - 'MeanSquaredError'
  - 'StructuralSimilarityIndexMeasure'
  - 'LearnedPerceptualImagePatchSimilarity'