repo_id: "Kytolly/FollowBench"
assets:
  path: "assets/followbench"
output:
  path: "output/"
device: "cuda:2"
rules:
  clip_len: 600
  fps: 60
  resolution_height: 704
  resolution_width: 1280
dimensions:
  - mse
  - ssim
  - lpips
submission:
  source_path: "assets/kling"
  json_path: "templates/submission_kling.json"