test:
  repo_id: "Kytolly/examples_Ego2ExoFollowCamera"
  repo_feeaback_id : "Kytolly/feedback_Ego2ExoFollowCamera"
  repo_submission_id: "Kytolly/submission_Ego2ExoFollowCamera"
  path_assets: "assets/"
  models:
    wham_vit_h: "third-party/WHAM/checkpoints/wham_vit_bedlam_w_3dpw.pth.tar"
  rules:
    clip_len: 300
    fps: 60
    resolution_height: 704
    resolution_width: 1280
  submission:
    submission_path: "cache/gen/submission.json"
    source_path: "assets/test/"
    total_cases_num: 120
    resolution_height: 704
    resolution_width: 1280
    clip_fps: 60
    clip_len: 300
prod:
  repo_id: "Kytolly/examples_Ego2ExoFollowCamera"
  repo_feeaback_id : "Kytolly/feedback_Ego2ExoFollowCamera"
  repo_submission_id: "Kytolly/submission_Ego2ExoFollowCamera"
  path_assets: "assets/"
  models:
    wham_vit_h: "third-party/WHAM/checkpoints/wham_vit_bedlam_w_3dpw.pth.tar"
  rules:
    clip_len: 300
    fps: 60
    resolution_height: 704
    resolution_width: 1280
  submission:
    submission_path: "cache/gen/submission.json"
    source_path: "assets/test/"
    total_cases_num: 120
    resolution_height: 704
    resolution_width: 1280
    clip_fps: 60
    clip_len: 300
dev:
  repo_id: "Kytolly/examples_Ego2ExoFollowCamera"
  repo_feeaback_id : "Kytolly/feedback_Ego2ExoFollowCamera"
  repo_submission_id: "Kytolly/submission_Ego2ExoFollowCamera"
  path_assets: "assets/"
  models:
    wham_vit_h: "third-party/WHAM/checkpoints/wham_vit_bedlam_w_3dpw.pth.tar"
  rules:
    clip_len: 300
    fps: 60
    resolution_height: 704
    resolution_width: 1280
  submission:
    submission_path: "cache/gen/submission.json"
    source_path: "assets/test/"
    total_cases_num: 120
    resolution_height: 704
    resolution_width: 1280
    clip_fps: 60
    clip_len: 300