repo_id: "Kytolly/FollowBench"
device: "cuda"
assets:
  path: "assets/"
output:
  path: "output_worldwander_seen/"
rules:
  clip_len: 49
  fps: 60
  height: 704
  width: 1280
submission:
  source_path: "data/worldwander/test_unseen"
  json_path: "templates/submission_worldwander_seen.json"
meta:
  team_name: "Showlab"
  model_name: "WorldWander"
  split: "test_seen"
  contact: "kytolly.xqy@gmail.com"
metrics:
  - 'MeanSquaredError'
  - 'StructuralSimilarityIndexMeasure'
  - 'LearnedPerceptualImagePatchSimilarity'
  - 'PeakSignaltoNoiseRatio'