ASSETS_PATH:
  EGO: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/ego_compressed.mp4'
  EXO: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/exo_compressed.mp4'
  REF: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/exo_ref.png'
BASELINE_OUTPUTS:
  COGVIDEO: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/output_tps_exo_baseline_LTX.mp4'
  LTX: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/output_tps_exo_baseline_LTX.mp4'
  SVDXT: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/output_tps_exo_baseline_SVD_XT.mp4'
  WANI2V: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/output_tps_exo_baseline_wan_i2v.mp4'
  WANVACE: 'D:/Desktop/xqy/NUS311/FYP/project/Ego2ExowithMotion/data/output/output_tps_exo_baseline_wan_vace.mp4'
DEVICE: 'cuda:0'
FVD:
  STYLEGANV_REPO_PATH: 'D:/Desktop/xqy/NUS311/FYP/library/stylegan-v'
  MIRROR: 1
  GPUS: 1
  RESOLUTION: 224
  METRICS: 'fvd2048_16f'